### PR TITLE
Add support for adding message tag to bubbles to allow sending messag…

### PR DESCRIPTION
**Pull request by ryacobi**
…es outside of the 24h window

https://developers.facebook.com/docs/messenger-platform/send-api-reference/tags

### CODE REVIEW

**Comment by marceloverdijk** [comment]
Thx, I will look into it this week!

**Comment by ryacobi** [comment]
Great, thanks. The ENUM I've added will later be able to be replaced with
an Enum from the FB library, but they are yet to add anything about it.

*Ronen Yacobi *| Co-Founder & CTO
Mobile: +972·54·5207111
Skype: ronen.yacobi
*Download Drippler on the **App Store
<https://itunes.apple.com/app/drippler-updates-tips-apps/id619307903>
& **Google
Play
<https://play.google.com/store/apps/details?id=com.drippler.android.updates>*
*!*

**Comment by marceloverdijk** [comment]
Also raised https://github.com/restfb/restfb/issues/712

**Comment by marceloverdijk** [comment]
Hi @ryacobi I will pick this up as part of Messenger Platform v2.0 update released this week @F8 (https://github.com/marsbits/restfbmessenger/issues/9).

**Comment by ryacobi** [comment]
Great, are you merging in the meanwhile?

**Comment by ryacobi** [comment]
Hi Marcel, 
Any updates?

**Comment by marceloverdijk** [comment]
Hi @ryacobi I will make a new release this weekend.

**Comment by marceloverdijk** [comment]
Closed as per `v1.3.0` release.

**Comment by marceloverdijk** [comment]
@ryacobi `v1.3.0` is published to Maven Central and should be available soon after sync.
Note I removed the `MessageTagEnum` in favour of a `MessageTag` class as the available tag are not limited to the initial 3.

**Pull request closed without merging**
